name: remark_money
description: A simple personal accounting app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 基础依赖
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  share_plus: ^7.2.1

  # 图表
  fl_chart: ^0.63.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # 静态资源目录
  assets:
    - assets/
